### ISSUE TITLE
Getting syntax error

### ISSUE THREAD

**Issue by ryanrohypnol** [bannsec/stegoVeritas#26] opened 2020-04-22 16:34 UTC
I updated my Kali and Stegoveritas stopped working, I tried running it with python2/3 - Any suggestions?

`Traceback (most recent call last):
  File "/usr/local/bin/stegoveritas", line 5, in <module>
    from stegoveritas.stegoveritas import main
  File "/usr/local/lib/python2.7/dist-packages/stegoveritas/__init__.py", line 2, in <module>
    from .stegoveritas import StegoVeritas
  File "/usr/local/lib/python2.7/dist-packages/stegoveritas/stegoveritas.py", line 213
    def file_name(self) -> str:
                        ^
SyntaxError: invalid syntax
`

**Comment by bannsec** [comment] 2020-04-22 16:53
So that example run is python2, which I don't believe will run. Can you verify your python version is 3.5+?

**Comment by ryanrohypnol** [comment] 2020-04-22 17:22
Yes, but I've also tried with Python3 and had a similar issue.

**Comment by bannsec** [comment] 2020-04-22 17:41
Is there a different error? The error you posted is basically python2 complaining about not understanding type hints.

Please show me the output of the following

```bash
apt-get update && apt-get install -y python3-venv python3-wheel
python3 -m venv ~/stego
source ~/stego/bin/activate
pip install stegoVeritas
python --version
stegoVeritas -h
```

**Comment by ryanrohypnol** [comment] 2020-04-22 17:51
![image](https://user-images.githubusercontent.com/44453666/80015919-6c032280-84a0-11ea-8e29-025f3593e217.png)

**Comment by ryanrohypnol** [comment] 2020-04-22 18:00
Also tried this @bannsec 
![image](https://user-images.githubusercontent.com/44453666/80016794-9ef9e600-84a1-11ea-8437-e91ca8fad463.png)

**Comment by bannsec** [comment] 2020-04-22 18:02
Looks like apt's install of wheel isn't getting setup correctly. This should work:

```bash
apt-get update && apt-get install -y python3-venv python3-pip
python3 -m venv ~/stego
source ~/stego/bin/activate
pip install wheel
pip install stegoVeritas
python --version
stegoVeritas -h
```

Yep -- it cannot be run directly. It's setup to run as a package.

**Comment by ryanrohypnol** [comment] 2020-04-22 18:05
Same error! 
![image](https://user-images.githubusercontent.com/44453666/80017191-33644880-84a2-11ea-8715-28e6b136ef8d.png)

I am super confused by this, I use your tool all the time. I didn't change anything, so I'm assuming others will have this problem.

**Comment by bannsec** [comment] 2020-04-22 18:09
So bdist_wheel is a build command. In your output, I'm seeing "Requirement already satisfied", which means python already built (even though it failed) previously. This means that the wheel command was never called, due to you already having previously attempted to build.

Did you `rm -rf ~/stego` first and then re-create that virtual env?

My gut feeling here is that on the first install of stegoVeritas on your updated kali, you probably ended up using pip2 (either knowingly or otherwise) instead of pip3.

**Comment by ryanrohypnol** [comment] 2020-04-22 18:13
It is case sensitive, you had a capital "V", I never had to run stegoveritas from a venv. How would you suggest I fix this? I appreciate the help.

![image](https://user-images.githubusercontent.com/44453666/80017853-33b11380-84a3-11ea-9f8c-3fb7d677feca.png)

**Comment by bannsec** [comment] 2020-04-22 18:19
Nice catch. I can add another alias if that would make it easier (i.e.: alias stegoVeritas->stegoveritas). I honestly don't think about it when I type lol.

**Comment by ryanrohypnol** [comment] 2020-04-22 18:31
@bannsec haha, It's up to you! The way I used it prior, was as easy as typing **stegoveritas file.jpg**, without any virtual environments. I'd love to know what was broken, so I don't have to go through that process anytime I want to use the tool :(

**Comment by bannsec** [comment] 2020-04-22 19:33
As far as i'm aware nothing is broken. My unit tests for kali still function properly. The only thing installing it to a virtualenv does is just tries to separate the libraries from the rest of your env and it's definitely not a requirement.

I just manually installed it on a bare kalilinux-rolling docker release and it installs just fine without a virtualenv.

**Comment by ryanrohypnol** [comment] 2020-04-22 19:34
@bannsec Okay, I'll keep digging. Thank you

**Comment by bannsec** [comment] 2020-04-22 19:35
np. wish i knew what was going on with your setup. For reference, here's what I did as a base test for kali:

```bash
sudo docker run -it --rm kalilinux/kali-rolling
```

Then inside the container
```bash
apt update && apt install python3 python3-pip
pip3 install stegoveritas
stegoveritas -h
```

**Comment by ryanrohypnol** [comment] 2020-04-22 19:39
@bannsec I fixed it with

`python3 -m pip install stegoveritas`

So strange!

**Comment by bannsec** [comment] 2020-04-22 19:56
Did you originally install as `pip install`? If so, your `pip` is probably for python2. You can check with

```bash
pip --version
```

**Comment by ryanrohypnol** [comment] 2020-04-22 20:02
Yes, but I've been using StegoVeritas for at least 6 months with no issues. My pip installation is python2.7, so for newer installations I use pip3. I'm sure i'll have to figure out the actual problem soon. We'll see!

**Comment by bannsec** [comment] 2020-05-03 15:29
Closing this issue for now. If you can give me steps to reproduce (inside kali docker would be easiest), then plz reopen.

**Closed by bannsec** 2020-05-03 15:29 UTC
